packages:
  - sdk
  - tools/*

autoInstallPeers: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - lefthook
  - nx
  - prisma

strictPeerDependencies: false
