services:
  postgres:
    image: postgres:16
    container_name: telareth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: telarethadmin
      POSTGRES_PASSWORD: telarethpass
      POSTGRES_DB: telareth
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
