services:
  postgres:
    image: postgres:16
    container_name: telareth-postgres
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASS}'
      POSTGRES_DB: '${DATABASE_NAME}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
