name: CI
on: [push, pull_request]

jobs:
  namae-no-eda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dcdavidev/namae-no-eda@ad313dfe0ef811820ce62a3ee30462ce52b7ebcb
