name: Branch Name Lint
on: [push, pull_request]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx validate-branch-name
